name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GiHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Publish the Docker image
      run: |
        docker build . --file Dockerfile.pulumi-devcontainer --tag ghcr.io/dah4k/pulumi-devcontainer:latest --tag ghcr.io/dah4k/pulumi-devcontainer:$(date +%Y%m%d)
        docker push ghcr.io/dah4k/pulumi-devcontainer:$(date +%Y%m%d)
        docker push ghcr.io/dah4k/pulumi-devcontainer:latest
